[General]
sIntroSequence=TCGISO.BIK
bModManagerMenuEnabled=1
sLanguage=ENGLISH

[Archive]
bInvalidateOlderFiles=1
sArchiveToLoadInMemoryList=Skyrim - Animations.bsa
sEsmToLoadInMemoryList=Skyrim.esm, Update.esm, Dawnguard.esm, HearthFires.esm, Dragonborn.esm, TCGiSOLux Master Plugin Interior.esm
sResourceArchiveList=Skyrim - Misc.bsa, Skyrim - Shaders.bsa, Skyrim - Interface.bsa, Skyrim - Animations.bsa, Skyrim - Meshes0.bsa, Skyrim - Meshes1.bsa, Skyrim - Sounds.bsa
sResourceArchiveList2=Skyrim - Voices_en0.bsa, Skyrim - Textures0.bsa, Skyrim - Textures1.bsa, Skyrim - Textures2.bsa, Skyrim - Textures3.bsa, Skyrim - Textures4.bsa, Skyrim - Textures5.bsa, Skyrim - Textures6.bsa, Skyrim - Textures7.bsa, Skyrim - Textures8.bsa
sResourceArchiveList3=Abdulaziz Artikov - Meshes.bsa, Abdulaziz Artikov - Textures.bsa, Abdulaziz Artikov - Textures1.bsa, Abdulaziz Artikov - Textures2.bsa, Abdulaziz Artikov - Voices.bsa, Abdulaziz Artikov - Scripts.bsa

[SaveGame]
iAutoSaveCount=5

[Actor]
; USSEP: Fixes bow engagement distance
fVisibleNavmeshMoveDist=12288.0000

[Display]
; Disables bloom
fGlobalBloomThresholdBoost=10
; Disables Screen Space Reflections - fixes engine bug with green water. Use ENB for better implementation (you may need to remove this, then).
fWaterSSRIntensity=0.0001
; Fix a transparent rectangle on the screen - this is a SkyrimPrefs.ini setting, which cannot be changed from this file, must be added manually
; iShadowMaskQuarter=4

[Interface]
; Closer book and note zooming
fBookDistance=82.0000
fNoteDistance=70.0000
fBookOpenTime=500.0000
fInventoryLight2DimmerValue=2.0000
fInventoryLightDimmerValue=1.0000
fInventory3DBoundRadiusScale=12.5000
fInventory3DItemRotMouseSpeed=50.0000
fInventory3DItemRotSpeed=3.0000
fInventory3DItemZoomScale=4.000
fInventory3DItemZoomZ=0.0000
fInventory3DItemZoomY=-500.0000
fInventory3DItemZoomX=0.0000
fInventory3DItemZoomSpeed=1.5000
fInventory3DItemPosScaleWide=1.5000
fInventory3DItemPosZWide=12.0000
fInventory3DItemPosYWide=-500.0000
fInventory3DItemPosXWide=-29.0000
fInventory3DItemPosScale=1.8700
fInventory3DItemPosZ=16.0000
fInventory3DItemPosY=-500.0000
fInventory3DItemPosX=-38.0000
bShowInventory3D=1
